-- Kaisen Phase 1: products and optimistic-version foundation.
-- No down migration is provided by design.

create table public.products (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses (id) on delete restrict,
  nombre text not null check (btrim(nombre) <> ''),
  precio numeric(12, 2) not null check (precio >= 0),
  stock integer not null default 0 check (stock >= 0),
  categoria text not null check (btrim(categoria) <> ''),
  codigo_barras text null,
  activo boolean not null default true,
  deleted_at timestamptz null,
  version bigint not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid not null references auth.users (id),
  updated_by uuid not null references auth.users (id),
  constraint products_business_id_id_key unique (business_id, id),
  constraint products_barcode_not_blank
    check (codigo_barras is null or btrim(codigo_barras) <> '')
);

create unique index products_active_barcode_uidx
on public.products (business_id, lower(codigo_barras))
where activo = true and codigo_barras is not null;

create index products_active_name_idx
on public.products (business_id, activo, nombre);

create index products_updated_at_idx
on public.products (business_id, updated_at);
