-- Kaisen Phase 1: sales, sale lines and compatible history view.
-- No down migration is provided by design.

create table public.sales (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses (id) on delete restrict,
  client_operation_id uuid not null,
  payload_hash text not null check (btrim(payload_hash) <> ''),
  seller_id uuid not null references auth.users (id),
  occurred_at timestamptz not null default now(),
  total numeric(12, 2) not null check (total >= 0),
  created_at timestamptz not null default now(),
  constraint sales_business_id_id_key unique (business_id, id),
  constraint sales_operation_uidx unique (business_id, client_operation_id)
);

create index sales_business_occurred_at_idx
on public.sales (business_id, occurred_at desc);

create table public.sale_items (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses (id) on delete restrict,
  sale_id bigint not null,
  product_id bigint not null,
  producto_nombre text not null check (btrim(producto_nombre) <> ''),
  categoria text not null check (btrim(categoria) <> ''),
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12, 2) not null check (precio_unitario >= 0),
  line_total numeric(12, 2) not null check (line_total >= 0),
  created_at timestamptz not null default now(),
  constraint sale_items_sale_business_fk
    foreign key (business_id, sale_id)
    references public.sales (business_id, id)
    on delete restrict,
  constraint sale_items_product_business_fk
    foreign key (business_id, product_id)
    references public.products (business_id, id)
    on delete restrict,
  constraint sale_items_sale_product_uidx unique (sale_id, product_id)
);

create index sale_items_business_product_idx
on public.sale_items (business_id, product_id);

create index sale_items_sale_idx
on public.sale_items (sale_id);

-- The current Flutter history is line-oriented, so this view deliberately
-- returns one row per sale item while retaining the numeric sale_id.
create view public.sale_history
with (security_invoker = true)
as
select
  si.id,
  si.business_id,
  si.sale_id,
  si.product_id as producto_id,
  si.producto_nombre,
  si.categoria,
  si.cantidad,
  si.precio_unitario,
  si.line_total as total,
  s.occurred_at as fecha,
  s.seller_id,
  s.client_operation_id,
  s.created_at
from public.sale_items as si
join public.sales as s
  on s.business_id = si.business_id
 and s.id = si.sale_id;
