CREATE DATABASE IF NOT EXISTS kaisen_db CHARACTER SET utf8mb4;
USE kaisen_db;

CREATE TABLE IF NOT EXISTS productos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  precio DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  codigo_barras VARCHAR(64) NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ventas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  producto_id INT NOT NULL,
  producto_nombre VARCHAR(255) NOT NULL,
  categoria VARCHAR(100) NOT NULL DEFAULT 'Sin categoría',
  cantidad INT NOT NULL,
  precio_unitario DECIMAL(10,2) NOT NULL,
  fecha DATETIME NOT NULL
);
